name: BroadcastUi
main: DeadBush\BroadcastUi\Main
api: [3.0.0, 4.0.0]
author: DeadBush
version: 1.0
description: A BroadcastUi plugin for PocketMine-MP

commands:
  bc:
    description: "Open A UI For Broadcast"